// Language-neutral fields (slug, id, tags, github, media, stack tech names)
// live alongside localized `en` / `ja` content blocks. Tech/stack values stay
// in English in both languages; only labels and prose are translated.

export const projects = [
  {
    slug: "gmail-ai",
    id: "gmail",
    index: "01",
    wordmark: "Gmail AI",
    tags: ["Next.js", "TypeScript", "Claude API", "Gmail API", "SQLite"],
    github: "https://github.com/tatsuya2607/Gmail_AI",
    live: null,
    cover: "/works/gmail/poster.webp",
    heroVideo: "/works/gmail/gmail-ai-demo.mp4",
    media: [
      { type: "image", src: "/works/gmail/home.webp", alt: "Dashboard listing the linked Gmail account, template count, and connection status" },
      { type: "image", src: "/works/gmail/inbox.webp", alt: "Inbox with message list, labels sidebar, and account switcher" },
      { type: "image", src: "/works/gmail/templates.webp", alt: "Template manager for saving reusable reply instructions" },
    ],
    stack: {
      Framework: ["Next.js 15 (App Router)", "TypeScript"],
      AI: ["Anthropic Claude API (Haiku / Sonnet)", "Server-sent streaming"],
      Auth: ["Google OAuth 2.0 (offline access)", "AES-256-GCM token encryption"],
      Data: ["better-sqlite3", "Gmail API (googleapis)"],
      UI: ["Custom CSS themes", "Light / dark mode synced to OS"],
    },
    en: {
      title: "Gmail AI Reply",
      tagline: "Reply to Gmail without leaving your inbox — assisted by Claude.",
      overview: [
        "Built to remove the back-and-forth between Gmail and an AI chat window. The flow is single-screen: open the inbox, pick a message, dictate intent in plain language, watch Claude stream a reply, edit, and send — all without copy-paste.",
        "Multiple Google accounts can be linked through OAuth and switched at runtime. Tokens are stored locally with AES-256-GCM, and thread headers are preserved so replies thread correctly on the Gmail side.",
      ],
      features: [
        { title: "Multi-account Gmail with OAuth 2.0", body: "Link any number of Google accounts and switch between them at runtime. Tokens are encrypted at rest with AES-256-GCM." },
        { title: "Model switching: Haiku ↔ Sonnet", body: "Toggle between Claude Haiku for fast/economical drafts and Claude Sonnet when reply quality matters." },
        { title: "Streaming output", body: "Replies render token-by-token with a typewriter animation so review starts before generation finishes." },
        { title: "Thread-preserving replies", body: "In-Reply-To and References headers are written automatically, so threads stay intact on Gmail's side." },
        { title: "Reusable instruction templates", body: "Save common reply directives (tone, language, signature) and apply them with one click." },
        { title: "Rule-based auto-labeling", body: "Tag incoming mail by sender domain or address, similar to filters but evaluated client-side." },
        { title: "Local SQLite cache", body: "Message lists are cached for 3 minutes with better-sqlite3, cutting initial load on revisit." },
      ],
      learnings: [
        "Designing around streaming changes how you think about UI state — partial output has to look intentional, not flickery.",
        "OAuth refresh flows and at-rest token encryption need a clear lifecycle; treating them as an afterthought leaks complexity into every route.",
        "Threading a reply correctly is a header concern, not a body concern. RFC-correct In-Reply-To / References was the single highest-leverage detail.",
      ],
    },
    ja: {
      title: "Gmail AI Reply",
      tagline: "受信トレイを離れず、Claudeの力でGmailに返信する。",
      overview: [
        "GmailとAIチャット画面を行き来する手間をなくすために作りました。フローは1画面で完結します。受信トレイを開き、メールを選び、自然な言葉で指示を出すと、Claudeが返信をストリーミング生成。編集してそのまま送信でき、コピー&ペーストは不要です。",
        "複数のGoogleアカウントをOAuthで連携し、実行時に切り替えられます。トークンはAES-256-GCMでローカルに暗号化保存し、スレッドヘッダーを保持するためGmail側でも返信が正しくスレッド表示されます。",
      ],
      features: [
        { title: "OAuth 2.0による複数Gmailアカウント管理", body: "任意の数のGoogleアカウントを連携し、実行時に切り替え可能。トークンはAES-256-GCMで暗号化して保存します。" },
        { title: "モデル切替: Haiku ↔ Sonnet", body: "高速・低コストな下書きにはClaude Haiku、返信の品質を重視する場面ではClaude Sonnetを使い分けられます。" },
        { title: "ストリーミング出力", body: "返信はタイプライター風アニメーションで1トークンずつ表示され、生成完了を待たずに内容を確認し始められます。" },
        { title: "スレッドを保持する返信", body: "In-Reply-To / References ヘッダーを自動付与するため、Gmail側でもスレッドが崩れません。" },
        { title: "再利用できる指示テンプレート", body: "よく使う返信の指示（トーン・言語・署名など）を保存し、ワンクリックで適用できます。" },
        { title: "ルールベースの自動ラベリング", body: "送信元ドメインやアドレスで受信メールを自動タグ付け。フィルタに近い仕組みをクライアント側で評価します。" },
        { title: "ローカルSQLiteキャッシュ", body: "better-sqlite3でメール一覧を3分間キャッシュし、再訪時の初期読み込みを短縮します。" },
      ],
      learnings: [
        "ストリーミングを前提に設計すると、UIの状態の捉え方が変わります。途中の出力も「意図された表示」に見せる必要があり、チラつかせてはいけません。",
        "OAuthのリフレッシュフローとトークンの暗号化保存には明確なライフサイクル設計が必要で、後回しにすると複雑さが全ルートに漏れ出します。",
        "返信を正しくスレッド化するのは本文ではなくヘッダーの問題。RFCに沿った In-Reply-To / References が最も効果の大きいディテールでした。",
      ],
    },
  },
  {
    slug: "jsa-website",
    id: "culture",
    index: "02",
    wordmark: "JSA Site",
    tags: ["React 19", "Vite", "Tailwind CSS", "Firebase", "React Router 7"],
    github: "https://github.com/tatsuya2607/JSA-website",
    live: "https://jsa-website-ivory.vercel.app",
    cover: "/works/jsa/hero.webp",
    media: [
      { type: "image", src: "/works/jsa/about.webp", alt: "About section with Community, Events, and Experience feature cards" },
      { type: "image", src: "/works/jsa/culture.webp", alt: "Japanese Culture section with Arts & Crafts and Food & Cuisine cards" },
      { type: "image", src: "/works/jsa/events.webp", alt: "Events page with category filter and event card grid" },
      { type: "image", src: "/works/jsa/admin-login.webp", alt: "Admin login screen gated by Firebase Authentication" },
      { type: "image", src: "/works/jsa/admin-dashboard.webp", alt: "Admin dashboard with Events, Team, and Site Review cards" },
      { type: "image", src: "/works/jsa/admin-events.webp", alt: "Admin events management with editable, publishable event list" },
      { type: "image", src: "/works/jsa/admin-team.webp", alt: "Admin team management with member CRUD form and ordered member list" },
    ],
    stack: {
      Framework: ["React 19", "Vite 7", "React Router 7"],
      UI: ["Tailwind CSS", "Headless UI", "Heroicons / React Icons"],
      Backend: ["Firebase Authentication", "Cloud Firestore", "Cloud Storage"],
      Tooling: ["ESLint", "PostCSS"],
    },
    en: {
      title: "JSA — Japanese Culture Site",
      tagline: "A public site and admin console for a Japanese Student Association.",
      overview: [
        "A learning project deliberately scoped to real operations: a public site visitors can browse, plus a protected admin console maintainers can use to keep content fresh — both shipping from the same codebase.",
        "Content is stored in Firestore and images in Cloud Storage, with Firebase Authentication gating every admin route through a ProtectedRoute wrapper.",
      ],
      features: [
        { title: "Public sections", body: "Hero, About, Culture, Events, Team, and Contact — composed from reusable layout/section components." },
        { title: "Event listing with category filter", body: "Filters bind to URL queries (?category=…) so filtered views are linkable and reload-safe." },
        { title: "Authenticated admin dashboard", body: "Firebase Authentication backs login. /admin, /admin/events, and /admin/team are protected; unauthenticated visits redirect to /admin-login and return after sign-in." },
        { title: "Events & team CRUD", body: "Create, edit, and delete events and team members directly from the admin UI." },
        { title: "Image upload to Cloud Storage", body: "Event and team images upload to Firebase Storage with timestamped paths to avoid collisions." },
      ],
      learnings: [
        "Co-locating a public site and an authenticated admin in one repo forces you to think about route boundaries early — ProtectedRoute became the central seam.",
        "Firebase client config is meant to be public; the security work lives in Firestore/Storage Rules. That mental model took a beat to absorb.",
        "URL-as-state for filters is a small choice that pays back constantly: shareable links, refresh safety, browser back/forward all 'just work'.",
      ],
    },
    ja: {
      title: "JSA — 日本文化サイト",
      tagline: "日本人学生団体（JSA）のための公開サイト兼管理コンソール。",
      overview: [
        "実運用を意識して範囲を絞った学習プロジェクトです。来訪者が閲覧できる公開サイトと、運営者がコンテンツを更新できる認証付き管理コンソールを、同じコードベースから提供しています。",
        "コンテンツはFirestore、画像はCloud Storageに保存。Firebase Authenticationで、すべての管理ルートを ProtectedRoute ラッパー経由で保護しています。",
      ],
      features: [
        { title: "公開ページ", body: "Hero / About / Culture / Events / Team / Contact を、再利用可能なレイアウト・セクションコンポーネントで構成。" },
        { title: "カテゴリフィルタ付きイベント一覧", body: "フィルタをURLクエリ（?category=…）と連動させ、絞り込み後の表示もリンク共有・リロードに対応します。" },
        { title: "認証付き管理ダッシュボード", body: "Firebase Authenticationでログインを管理。/admin・/admin/events・/admin/team は保護され、未ログイン時は /admin-login にリダイレクト後、元のページへ復帰します。" },
        { title: "イベント・メンバーのCRUD", body: "イベントやチームメンバーの作成・編集・削除を、管理画面から直接行えます。" },
        { title: "Cloud Storageへの画像アップロード", body: "イベントやメンバーの画像を、衝突を避けるためタイムスタンプ付きパスでFirebase Storageにアップロードします。" },
      ],
      learnings: [
        "公開サイトと認証付き管理画面を1つのリポジトリに同居させると、ルートの境界を早い段階で意識せざるを得ません。ProtectedRoute が設計の中心になりました。",
        "Firebaseのクライアント設定は公開される前提で、セキュリティの本体は Firestore / Storage のルールにあります。この考え方を腹落ちさせるのに少し時間がかかりました。",
        "フィルタの状態をURLに持たせるのは小さな選択ですが、リンク共有・リロード耐性・ブラウザの戻る/進むが自然に機能し、繰り返し効いてきます。",
      ],
    },
  },
  {
    slug: "matcha-cafe-lp",
    id: "matcha",
    index: "03",
    wordmark: "Matcha LP",
    tags: ["Next.js", "TypeScript", "next-intl", "i18n", "Vercel"],
    github: "https://github.com/tatsuya2607/matcha-cafe-lp",
    live: "https://matcha-cafe-lp.vercel.app",
    cover: "/works/matcha/hero.webp",
    media: [
      { type: "image", src: "/works/matcha/about.webp", alt: "About section introducing the café beside a matcha latte and tokonoma" },
      { type: "image", src: "/works/matcha/menu.webp", alt: "Menu section with tabbed seasonal matcha drinks, sweets, and sets" },
      { type: "image", src: "/works/matcha/story.webp", alt: "Story section laying out the four-step matcha-making craft" },
      { type: "image", src: "/works/matcha/gallery.webp", alt: "Gallery grid of the renovated machiya interior and courtyard" },
      { type: "image", src: "/works/matcha/visit.webp", alt: "Visit section with hours, phone, and Instagram link" },
    ],
    stack: {
      Framework: ["Next.js 15 (App Router)", "React 19", "TypeScript"],
      i18n: ["next-intl", "Locale-prefixed routing (/ja, /en)"],
      UI: ["Hand-written CSS (wa-modern theme)", "Scroll-reveal & micro-interactions"],
      Fonts: ["next/font", "Cormorant Garamond", "Noto Serif / Sans JP"],
      Tooling: ["sharp (WebP optimization)", "Vercel (SSG deploy)"],
    },
    en: {
      title: "Kissa Midori — Matcha Café LP",
      tagline: "A bilingual, wa-modern landing page for a fictional matcha café in Gion, Kyoto.",
      facts: [
        { label: "Build time", value: "About 1 week" },
        { label: "Scope", value: "Design → implementation → deploy" },
        { label: "Responsive", value: "Mobile · tablet · desktop" },
        { label: "Format", value: "Single-page LP, bilingual (JA / EN)" },
        { label: "Performance", value: "Lighthouse (desktop): 88 Performance · 95 Accessibility · 100 Best Practices · 91 SEO" },
      ],
      overview: [
        "A production-grade marketing landing page for a matcha café, built as a portfolio piece. It targets two audiences — locals in Kyoto and overseas matcha lovers visiting Japan — so the whole site switches between Japanese and English with a single click. There's no reservation or e-commerce flow; it's an information / brand site focused on atmosphere, craft, and conversion to an in-person visit.",
        "The visual base started from a Claude Design HTML mockup and was rebuilt from scratch as a fully typed, internationalized Next.js application. All copy and content data live in JSON catalogs, and every photo is an original asset served as optimized WebP.",
      ],
      features: [
        { title: "Full bilingual support (JA / EN)", body: "next-intl with locale-prefixed routing (/ja, /en) and an in-nav language switcher. All copy lives in JSON catalogs kept in sync across both languages." },
        { title: "Distinctive wa-modern design", body: "First-harvest matcha greens, warm cream tones, and a Cormorant Garamond × Noto Serif/Sans JP type pairing — all hand-authored CSS with no UI kit." },
        { title: "Crafted micro-interactions", body: "Scroll-reveal animations, an animated count-up for stats, a slow hero pan, a scroll-progress bar, and a subtle film-grain texture." },
        { title: "All-original imagery", body: "Every photo — menu, interior, hero — is a custom asset, served as resized WebP from public/images." },
        { title: "Accessible & resilient", body: "Keyboard focus styles, ARIA labels, and full prefers-reduced-motion support." },
        { title: "Fast by default", body: "Statically generated per locale (SSG), WebP imagery (source PNGs ~40 MB → ~1.7 MB), optimized fonts via next/font, and an SEO / Open Graph metadata layer." },
      ],
      learnings: [
        "Designing for two languages from the start changes layout decisions — line lengths, font pairings, and component spacing all have to hold up in both JA and EN.",
        "Locale-prefixed routing with next-intl is clean once the middleware and routing config are set up correctly; getting redirects right was the fiddly part.",
        "Image weight dominates a photo-heavy brand site. Converting and resizing to WebP with sharp (~40 MB → ~1.7 MB) was the single biggest performance win.",
      ],
    },
    ja: {
      title: "喫茶みどり — 抹茶カフェ LP",
      tagline: "京都・祇園の架空の抹茶カフェを題材にした、和モダン × 二言語対応のランディングページ。",
      facts: [
        { label: "制作期間", value: "約1週間" },
        { label: "対応範囲", value: "デザイン → 実装 → デプロイまで一貫" },
        { label: "レスポンシブ", value: "モバイル・タブレット・デスクトップ対応" },
        { label: "構成", value: "1ページ完結型LP／日英2言語対応" },
        { label: "表示速度", value: "Lighthouse（デスクトップ）Performance 88 ・ A11y 95 ・ Best Practices 100 ・ SEO 91" },
      ],
      overview: [
        "ポートフォリオ用に制作した、抹茶カフェの集客用ランディングページです。ターゲットは「京都の地元客」と「抹茶を目当てに訪日する海外客」の二層。そのため、サイト全体を日本語・英語ワンクリックで切り替えられる構成にしています。予約・EC機能は持たず、空間と作り手のこだわりを伝えて来店につなげる、情報・ブランドサイトとして設計しました。",
        "ビジュアルの土台は Claude Design の HTML モックアップから出発し、型安全で多言語対応の Next.js アプリとしてゼロから再構築しています。文言・コンテンツデータはすべて JSON で一元管理し、写真はすべて自前素材を最適化済み WebP で配信しています。",
      ],
      features: [
        { title: "完全な日英対応（JA / EN）", body: "next-intl によるロケール付きルーティング（/ja・/en）とナビ内の言語スイッチャー。文言はすべて JSON で一元管理し、両言語でキーを同期しています。" },
        { title: "個性のある和モダンデザイン", body: "一番摘み抹茶のグリーンと温かいクリーム色、Cormorant Garamond × Noto Serif/Sans JP の組み合わせ。UIキットに頼らない手書きCSSです。" },
        { title: "作り込んだ演出", body: "スクロールリビール、数値カウントアップ、ヒーローのゆるやかなパン、スクロール進捗バー、フィルムグレインの質感。" },
        { title: "全画像がオリジナル", body: "メニュー・店内・ヒーローの写真はすべて自前素材で、public/images からリサイズ済みWebPとして配信しています。" },
        { title: "アクセシビリティ配慮", body: "キーボードフォーカス、ARIAラベル、prefers-reduced-motion に対応しています。" },
        { title: "高速", body: "ロケール別の静的生成（SSG）、WebP最適化画像（元PNG約40MB → 約1.7MB）、next/font によるフォント最適化、SEO/OGメタ対応。" },
      ],
      learnings: [
        "最初から二言語を前提に設計すると、行長・フォントの組み合わせ・余白など、レイアウトの判断が変わります。日英どちらでも破綻しないようにする必要があります。",
        "next-intl のロケール付きルーティングは、ミドルウェアとルーティング設定が整えば綺麗にまとまります。リダイレクトを正しく扱うのが細かく手のかかる部分でした。",
        "写真主体のブランドサイトでは画像の容量が支配的です。sharp で WebP に変換・リサイズした（約40MB → 約1.7MB）ことが、最も効果の大きいパフォーマンス改善でした。",
      ],
    },
  },
  {
    slug: "aura-buds",
    id: "aura",
    index: "04",
    wordmark: "Aura Buds",
    tags: ["HTML5", "CSS3", "JavaScript", "Canvas API", "Responsive"],
    github: "https://github.com/tatsuya2607/aura-buds-lp",
    live: "https://aura-buds-lp.vercel.app",
    cover: "/works/aura/hero.webp",
    media: [
      { type: "image", src: "/works/aura/design.webp", alt: "Design section with a macro shot of a single earbud" },
      { type: "image", src: "/works/aura/nc.webp", alt: "Adaptive noise cancelling section over a portrait" },
      { type: "image", src: "/works/aura/audio.webp", alt: "Spatial audio section with an animated waveform" },
      { type: "image", src: "/works/aura/specs.webp", alt: "Specs section with animated count-up stats" },
      { type: "image", src: "/works/aura/colors.webp", alt: "Four color variations with swatches" },
      { type: "image", src: "/works/aura/tech.webp", alt: "Engineering section with the earbud exploded into its internal components" },
      { type: "image", src: "/works/aura/life.webp", alt: "Lifestyle section with a full-bleed video of Aura Buds worn in everyday life" },
    ],
    stack: {
      Markup: ["HTML5 (semantic sections)"],
      Styling: ["Hand-written CSS", "Custom properties", "clamp() fluid type", "Alternating dark / light sections"],
      Interaction: ["Vanilla JavaScript", "Canvas API (particle field)", "IntersectionObserver reveals & count-up"],
      Media: ["HTML5 video (hero / engineering / lifestyle)", "ffmpeg processing (watermark removal, scaling)", "CSS mask edge-feathering"],
      Typography: ["Inter", "Noto Sans JP (Google Fonts)"],
      Approach: ["Apple-style product LP", "Single static page, no build step"],
    },
    en: {
      title: "Aura Buds — Product Landing Page",
      tagline: "An Apple-style product page for a fictional pair of noise-cancelling wireless earbuds.",
      overview: [
        "A marketing landing page for a fictional wireless earbud, built to study the restrained, high-end feel of Apple product pages. The whole thing ships as a single static HTML file — no framework, no build step — so the craft lives entirely in the CSS and a small amount of vanilla JavaScript.",
        "Nine sections alternate between dark and light to set a rhythm, and the copy leads with experience rather than spec sheets. The hero, engineering, and lifestyle sections use looping-free product video — AI-generated clips cleaned up with ffmpeg (watermark removal, scaling, edge-feathered masks) so they sit seamlessly on the black canvas. Every visual flourish has a reduced-motion fallback, so the page stays calm and usable when the viewer prefers less movement.",
      ],
      features: [
        { title: "Apple-style art direction", body: "Neutral palette with a single accent, oversized tight-tracked headings, and generous whitespace — dark and light sections alternate to pace the scroll." },
        { title: "Product video, watermark-free", body: "Hero (rotating product), engineering (exploded view), and lifestyle clips play once and rest. Source clips were processed with ffmpeg to remove watermarks, rescale, and feather their edges into the page background." },
        { title: "Canvas noise field", body: "The noise-cancelling section renders a particle field on a <canvas> that dissolves from noisy to silent as you scroll through it, mirroring the product's promise." },
        { title: "Spatial-audio waveform", body: "An animated SVG waveform layers three sine paths at different weights to suggest a living, three-dimensional soundstage." },
        { title: "Scroll-reveal & count-up", body: "IntersectionObserver fades sections in on entry and animates the spec numbers (24h, IPX4, 30dB) counting up with an ease-out curve." },
        { title: "Fluid, responsive layout", body: "Spacing and type scale with clamp() and viewport units, so the page holds its proportions from mobile to wide desktop without breakpoint clutter." },
        { title: "Motion-considerate", body: "Respects prefers-reduced-motion: the canvas, reveals, and count-ups all fall back to a static, fully-legible state." },
      ],
      learnings: [
        "With no framework or build step, the only thing keeping a single-file page maintainable is discipline — consistent naming and a clear section structure do the work a component tree usually would.",
        "Canvas effects look effortless but the work is tying their state to scroll progress without dropping frames; designing the reduced-motion fallback first kept that complexity from leaking everywhere.",
        "The 'luxury' of an Apple-style page comes from restraint — one accent color, big whitespace, slow ease-out motion — far more than from adding anything.",
      ],
    },
    ja: {
      title: "Aura Buds — 製品ランディングページ",
      tagline: "架空のノイズキャンセリング・ワイヤレスイヤホンのための、Apple系プロダクトページ。",
      overview: [
        "架空のワイヤレスイヤホンの集客用ランディングページです。Apple製品ページの、削ぎ落とされた高級感を研究するために制作しました。全体を1枚の静的HTMLファイルとして配信し、フレームワークもビルド工程も使っていません。そのため作り込みは、CSSとわずかなバニラJavaScriptにすべて宿っています。",
        "9つのセクションをダーク／ライトで交互に並べてリズムを作り、文言はスペックの羅列ではなく体験から語ります。Hero（回転）・Engineering（分解ビュー）・Lifestyle のセクションは、ループさせず一度だけ再生する製品動画を採用。AI生成のクリップを ffmpeg で加工（ウォーターマーク除去・リサイズ・縁のフェード）し、黒い画面に自然に溶け込ませています。すべての演出に「動きを抑える」フォールバックを用意し、prefers-reduced-motion 環境でも落ち着いて使えるようにしました。",
      ],
      features: [
        { title: "Apple系のアートディレクション", body: "ニュートラルな配色＋アクセント1色、字間を詰めた大きな見出し、たっぷりの余白。ダークとライトのセクションを交互に配置してスクロールにリズムを与えます。" },
        { title: "ウォーターマークを除去した製品動画", body: "Hero（回転）・Engineering（分解ビュー）・Lifestyle のクリップは一度だけ再生して静止します。元動画は ffmpeg でウォーターマーク除去・リサイズ・縁のフェード加工を施し、背景に馴染ませています。" },
        { title: "Canvasのノイズ表現", body: "ノイズキャンセリングのセクションでは <canvas> 上にパーティクルを描画し、スクロールに合わせて「騒がしい→静寂」へと溶けていく様子で製品の価値を表現します。" },
        { title: "空間オーディオの波形", body: "3本のサイン波を異なる太さで重ねたSVGアニメーションで、立体的に息づくサウンドステージを示唆します。" },
        { title: "スクロール演出とカウントアップ", body: "IntersectionObserver でセクションをフェードインさせ、スペックの数値（24時間・IPX4・30dB）をイージングしながらカウントアップ表示します。" },
        { title: "可変レスポンシブレイアウト", body: "余白とタイポを clamp() とビューポート単位でスケールさせ、ブレークポイントを増やさずにモバイルからワイドまで比率を保ちます。" },
        { title: "モーションへの配慮", body: "prefers-reduced-motion に対応。Canvas・リビール・カウントアップはすべて、静止した完全に読める状態にフォールバックします。" },
      ],
      learnings: [
        "フレームワークもビルド工程もないと、1枚もののページを保守可能に保つのは結局「規律」だけ。命名の一貫性と明快なセクション構造が、本来コンポーネントツリーが担う役割を引き受けます。",
        "Canvasの演出は簡単そうに見えて、本質はフレームを落とさずに状態をスクロール進捗へ結びつけること。動きを抑えるフォールバックを先に設計したことで、その複雑さが全体に漏れ出すのを防げました。",
        "Apple系ページの「高級感」は、何かを足すことよりも引き算から生まれます。アクセント1色、大きな余白、ゆっくりしたイージング。それで十分でした。",
      ],
    },
  },
  {
    slug: "task-planning",
    id: "planner",
    index: "05",
    wordmark: "AI Planner",
    tags: ["TypeScript", "Claude API", "Notion API", "Google Calendar", "GitHub Actions"],
    github: "https://github.com/tatsuya2607/task-planning",
    live: null,
    cover: "/works/planner/hero.webp",
    media: [
      { type: "image", src: "/works/planner/today-plan.webp", alt: "The Notion Today page showing the AI-generated, time-blocked daily schedule from morning gym to bedtime" },
      { type: "image", src: "/works/planner/task-db.webp", alt: "Task database grouped by axis, listing every task with status, project, priority, and due date" },
      { type: "image", src: "/works/planner/progress.webp", alt: "Progress summary page with an auto-updating dashboard table — per-axis progress bars, achievement rate, and completed/total" },
    ],
    stack: {
      Automation: ["TypeScript", "Node.js 22", "tsx", "GitHub Actions (cron)"],
      AI: ["Anthropic Claude API (Opus 4.8)", "Adaptive thinking", "Structured JSON output"],
      Integrations: ["Notion API (@notionhq/client v5, data sources)", "Google Calendar API (service account)"],
      Design: ["JST-normalized scheduling", "Idempotent, retry-safe writes"],
    },
    en: {
      title: "Notion AI Task Planner",
      tagline: "Every morning, an automation reads my calendar, tasks, and goals — then has Claude draft a time-blocked plan for my day.",
      overview: [
        "A serverless automation that runs entirely on GitHub Actions cron and writes into my Notion workspace. Each morning it gathers the day's fixed calendar events, my open tasks (with priority, due date, and time estimates), and my weekly skill goals, then asks Claude to produce a realistic, time-blocked schedule — respecting fixed events, leaving white space, and nudging long-term goals forward a little each day.",
        "A single Notion database is the source of truth; the today / this-week / all-tasks pages are just different views of it. A companion evening job stamps completions and writes a per-axis progress report. Capture happens from my phone: talking to Claude (via the Notion connector) files confirmed tasks, parks vague \"I want to try…\" ideas in a separate backlog, and answers progress questions — no laptop required.",
      ],
      features: [
        { title: "Morning AI planner", body: "Claude Opus 4.8 turns the day's calendar, open tasks, and weekly goals into a realistic hour-by-hour schedule, written straight into the Notion \"Today\" page." },
        { title: "Single source of truth", body: "One Notion task database backs everything; the today, this-week, and all-tasks pages are linked views of the same data, so nothing is duplicated." },
        { title: "Goal-driven scheduling", body: "A goals database holds weekly target hours per skill (AZ-900, IT Passport, web dev), so study time is scheduled deliberately instead of being forgotten." },
        { title: "Automatic progress tracking", body: "A nightly job stamps completion dates and writes per-axis achievement rates to a dated progress log." },
        { title: "Calendar-aware & JST-correct", body: "Fixed events are normalized to JST and kept free in the plan; the date and weekday are computed in JST, not the UTC runner's clock." },
        { title: "Mobile capture via chat", body: "From the phone, confirmed tasks go to the task DB (and Google Calendar), while aspirational ideas are parked in an ideas backlog — routed by intent." },
        { title: "Runs on free infrastructure", body: "Three cron workflows on GitHub Actions, no server to host; all credentials live in repository secrets." },
      ],
      learnings: [
        "Getting an LLM to output a usable plan is mostly about the inputs: structured task/goal context and hard constraints (fixed events, wake/sleep hours) matter far more than prompt wording.",
        "Timezone bugs hide inside the word \"today\". Computing the date and weekday in JST — not the UTC runner's clock — was a subtle but essential fix I only caught by reading a real run.",
        "Notion's API can't prepend or hide blocks, so the write strategy — marker-delimited sections vs. owning an entire page — became a real design decision rather than an afterthought.",
      ],
    },
    ja: {
      title: "Notion AI タスクプランナー",
      tagline: "毎朝、カレンダー・タスク・目標を読み取り、Claudeが「今日の時間割」を自動で組み立てる仕組み。",
      overview: [
        "GitHub Actions の cron だけで動くサーバーレスな自動化で、結果は自分の Notion に書き込まれます。毎朝、その日の固定予定（カレンダー）、未完了タスク（優先度・期限・所要時間つき）、週ごとのスキル目標を集め、Claude に「現実的で実行可能な時間割」を生成させます。固定予定は空けておき、余白も残し、長期目標を毎日少しずつ前進させる配分にします。",
        "唯一の台帳は1つの Notion タスクデータベースで、「今日 / 今週 / 全タスク」の各ページは、その同じDBを別々のビューで見せている「窓」です。夜のジョブが完了日をスタンプして軸別の達成率レポートを書き出します。入力はスマホから。Claude（Notion連携）に話すと、確定タスクはタスクDBへ、曖昧な「やってみたい」アイデアは別のリストへ振り分けられ、進捗の質問にも答えます。PCは不要です。",
      ],
      features: [
        { title: "毎朝のAIプランナー", body: "Claude Opus 4.8 が、その日のカレンダー・未完了タスク・週間目標から現実的な時間割を生成し、Notionの「今日」ページに直接書き込みます。" },
        { title: "唯一の台帳", body: "すべては1つの Notion タスクDBが土台。今日・今週・全タスクの各ページは同じデータのリンクドビューで、データは重複しません。" },
        { title: "目標ドリブンな配分", body: "目標DBにスキルごとの週あたり目標時間（AZ-900・ITパスポート・Web制作）を持たせ、学習時間を「忘れずに」意図的に組み込みます。" },
        { title: "自動の進捗トラッキング", body: "夜のジョブが完了日をスタンプし、軸別の達成率を日付つきの進捗ログに書き出します。" },
        { title: "カレンダー連動・JST厳密", body: "固定予定はJSTに正規化してプラン上で空けておき、日付と曜日もUTCランナーではなくJSTで算出します。" },
        { title: "チャットでモバイル入力", body: "スマホから、確定タスクはタスクDB（＋Googleカレンダー）へ、やりたいことアイデアは別リストへ、意図に応じて振り分けます。" },
        { title: "無料インフラで稼働", body: "GitHub Actions の cron 3本で動作し、サーバー不要。認証情報はすべてリポジトリの Secrets に保管します。" },
      ],
      learnings: [
        "LLMに使えるプランを出させる鍵は、ほぼ「入力」です。構造化したタスク/目標の文脈と、固定予定や起床・就寝といった厳密な制約のほうが、プロンプトの言い回しよりはるかに効きます。",
        "タイムゾーンのバグは「今日」という言葉の中に潜みます。日付と曜日をUTCランナーではなくJSTで計算すること——地味ですが必須の修正で、実際の実行ログを読んで初めて気づきました。",
        "Notion API は先頭挿入もブロックの非表示もできないため、書き込み方式（マーカーで囲む方式か、ページ全体を専有する方式か）が、後回しにできない設計判断になりました。",
      ],
    },
  },
];

export const projectsBySlug = Object.fromEntries(
  projects.map((p) => [p.slug, p])
);

export const getProject = (slug) => projectsBySlug[slug];
